"""Constants for the Apple TV Custom integration."""

DOMAIN = "apple_tv_custom"
APPLE_TV_DOMAIN = "apple_tv"

SERVICE_SEND_COMMAND = "send_command"
SERVICE_SEND_COMMAND_BUTTON = "button"

# Apple TV Commands
COMMAND_UP = "up"
COMMAND_DOWN = "down"
COMMAND_LEFT = "left"
COMMAND_RIGHT = "right"
COMMAND_SELECT = "select"
COMMAND_MENU = "menu"
COMMAND_PLAY_PAUSE = "play_pause"
COMMAND_HOME = "home"
COMMAND_HOME_HOLD = "home_hold"
COMMAND_POWER = "power"
COMMAND_VOLUME_UP = "volume_up"
COMMAND_VOLUME_DOWN = "volume_down"
COMMAND_NEXT_TRACK = "next_track"
COMMAND_PREVIOUS_TRACK = "previous_track"
COMMAND_SUSPEND = "suspend"
COMMAND_WAKEUP = "wakeup"
COMMAND_APP_LAUNCHER = "top_menu"
COMMAND_SKIP_FORWARD = "skip_forward"
COMMAND_SKIP_BACKWARD = "skip_backward"
COMMAND_TOGGLE_SUBTITLES = "toggle_subtitles" 